const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const { UPLOADS_DIR, removeUpload } = require('./files');

// Premium frame originals live outside uploads/ (which is served publicly);
// the public site only gets a small watermarked preview. Free frames are
// served from uploads/frames as before.
const PRIVATE_FRAMES_DIR = path.resolve(__dirname, '..', '..', 'private-uploads', 'frames');
const PUBLIC_FRAMES_DIR = path.join(UPLOADS_DIR, 'frames');
const PREVIEWS_DIR = path.join(PUBLIC_FRAMES_DIR, 'previews');

const PREVIEW_WIDTH = 480;
const PUBLIC_PREFIX = '/uploads/frames/';

const ensureDir = (dir) => fs.promises.mkdir(dir, { recursive: true });

// Stored file names are generated by the upload middleware; basename() keeps
// anything else from escaping the folder.
const privatePath = (name) => path.join(PRIVATE_FRAMES_DIR, path.basename(String(name)));

// '/uploads/frames/<file>' -> absolute path, or null for anything else
// (external URL, preview, legacy value).
const publicFramePath = (image) => {
  if (typeof image !== 'string' || !image.startsWith(PUBLIC_PREFIX)) return null;
  const name = image.slice(PUBLIC_PREFIX.length);
  if (!name || name.includes('/')) return null;
  return path.join(PUBLIC_FRAMES_DIR, name);
};

// Move across folders (rename, or copy + delete across devices).
const moveFile = async (from, to) => {
  await ensureDir(path.dirname(to));
  try {
    await fs.promises.rename(from, to);
  } catch (err) {
    if (err.code !== 'EXDEV') throw err;
    await fs.promises.copyFile(from, to);
    await fs.promises.unlink(from);
  }
};

const watermarkSvg = (width, height) => {
  const rows = [];
  for (let y = 40; y < height + 80; y += 90) {
    rows.push(`<text x="${width / 2}" y="${y}" text-anchor="middle" transform="rotate(-25 ${width / 2} ${y})">PREMIUM · AGSB · PREMIUM</text>`);
  }
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <style>text { font: bold 28px sans-serif; fill: rgba(255,255,255,0.45); stroke: rgba(0,0,0,0.35); stroke-width: 1px; }</style>
      ${rows.join('')}
    </svg>`
  );
};

// Small, watermarked WebP of a premium original (keeps transparency, which
// frame overlays rely on). Returns its public path.
const makePreview = async (originalName) => {
  await ensureDir(PREVIEWS_DIR);
  const base = path.parse(path.basename(originalName)).name;
  const previewName = `${base}-preview.webp`;
  const resized = await sharp(privatePath(originalName))
    .rotate()
    .resize({ width: PREVIEW_WIDTH, withoutEnlargement: true })
    .toBuffer({ resolveWithObject: true });
  await sharp(resized.data)
    .composite([{ input: watermarkSvg(resized.info.width, resized.info.height) }])
    .webp({ quality: 60 })
    .toFile(path.join(PREVIEWS_DIR, previewName));
  return `${PUBLIC_PREFIX}previews/${previewName}`;
};

// Place a freshly uploaded frame file (already in the private folder).
// Returns the fields to store: { image, original }.
const placeUpload = async (file, premium) => {
  if (premium) return { image: await makePreview(file.filename), original: file.filename };
  await moveFile(file.path, path.join(PUBLIC_FRAMES_DIR, file.filename));
  return { image: `${PUBLIC_PREFIX}${file.filename}`, original: null };
};

// Free -> premium for an existing frame: move its public file to the private
// folder and make a preview. Returns null when the image isn't a local upload
// (an external URL can't be protected).
const makePremium = async (frame) => {
  const from = publicFramePath(frame.image);
  if (!from || !fs.existsSync(from)) return null;
  const name = path.basename(from);
  await moveFile(from, privatePath(name));
  return { image: await makePreview(name), original: name };
};

// Premium -> free: publish the original. Returns null when there is none.
const makeFree = async (frame) => {
  if (!frame.original || !fs.existsSync(privatePath(frame.original))) return null;
  const name = path.basename(frame.original);
  await moveFile(privatePath(name), path.join(PUBLIC_FRAMES_DIR, name));
  return { image: `${PUBLIC_PREFIX}${name}`, original: null };
};

const removeOriginal = async (name) => {
  if (!name) return;
  try {
    await fs.promises.unlink(privatePath(name));
  } catch (err) {
    if (err.code !== 'ENOENT') console.error(`Could not delete frame original ${name}:`, err.message);
  }
};

module.exports = {
  PRIVATE_FRAMES_DIR,
  privatePath,
  publicFramePath,
  placeUpload,
  makePremium,
  makeFree,
  makePreview,
  removeOriginal,
  removeUpload,
};
